apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: back
  template:
    metadata:
      labels: 
        app: back
    spec:
      containers:
        - name: my-back
          imagePullPolicy: Always
          image: vomonong/my-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db-service:3306/test1
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort