apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: front
  template:
    metadata:
      labels: 
        app: front
    spec:
      containers:
        - name: my-front
          imagePullPolicy: Always
          image: vomonong/my-nginx:update
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort